stages:
  - build_image

master_push:
  stage: build_image
  variables:
    REGISTRY_ADDRESS: "registry.dnamicro.com"
    REGISTRY_USERNAME: "dev"
    REGISTRY_PASSWORD: "F0nch3rt0"
  script:
    - "docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD"
    - "docker build -t $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID -f dockerfile \
      --build-arg NODE_ENV=production \
      --build-arg PROJECT=$CI_PROJECT_NAME ."
    - "docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
    - "docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"
    - "docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
  only:
    - "master"
    - "staging"
    - "qa"
